# README: https://github.com/dart-lang/lints
# Rules: https://dart.dev/tools/linter-rules

# include: package:lints/core.yaml
include: package:lints/recommended.yaml # 使用建议规则，包含core
# analyzer:
#   exclude:
#     - lib/constant/constant.dart
#   errors:
#     invalid_assignment: warning
#     missing_return: error
#     dead_code: info

# linter:
#   rules:
#     file_names: false
#     constant_identifier_names: false
#     unnecessary_string_escapes: false #不必要的字符串转义
