name: top_one
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0+2000000001

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  logger: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^3.0.7
  crypto: ^3.0.2
  hive_flutter: ^1.1.0

  permission_handler: ^10.2.0
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0

  # 多语言
  # 本地创建自动locale_keys.g.dart文件的命令:
  # fvm flutter pub run easy_localization:generate --source-dir ./assets/translations/en --output-dir lib/gen -f keys -o locale_keys.gen.dart
  easy_localization: ^3.0.1

  dio: ^5.2.1+1
  flutter_downloader: ^1.10.4
  connectivity_plus: ^4.0.1

  firebase_crashlytics: ^3.0.11
  firebase_analytics: ^10.1.0
  google_mobile_ads: ^2.3.0
  # google_mobile_ads:
  #   path: packages/google_mobile_ads

  flutter_easyloading: ^3.0.5

  video_player: ^2.6.1
  cached_network_image: ^3.2.3
  # common_utils: ^2.1.0
  image_gallery_saver: ^2.0.2
  url_launcher: ^6.1.10
  in_app_review: ^2.0.6
  # introduction_screen: ^3.1.4

  gh_tool_package:
    # path: /Users/ginhoor/Workspace/Personal/Flutter/gh_tool_package
    git:
      url: https://github.com/ginhoor/GHToolPackage.git
      ref: 1.1.1

  flutter_tool_kit:
    git:
      url: https://github.com/AtlasXV/FlutterToolKit.git
      ref: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_gen_runner: ^5.3.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/translations/
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icon/ttd_icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  adaptive_icon_background: "assets/icon/ttd_icon.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon/ttd_icon.png" # only available for Android 8.0 devices and above
  image_path_ios: "assets/icon/ttd_icon.png"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 29
  remove_alpha_ios: true
  # web:
  #   generate: true
  #   image_path: "assets/images/icon-1024x1024.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "assets/images/icon-1024x1024.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "assets/images/icon-1024x1024.png"
# 生成资源映射
# fvm flutter packages pub run build_runner build
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # integrations: # Optional
  #   flutter_svg: true
  #   flare_flutter: true
  #   rive: true
  #   lottie: true
  assets:
    enabled: true # Optional
    outputs: # Optional
      # Optional
      # Set to true if you want this package to be a package dependency, See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false
      # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: dot-delimiter
      class_name: Assets
    exclude: []
  colors:
    enabled: true # Optional
    inputs: ["assets/color/colors.xml"] # Optional
    outputs: # Optional
      class_name: ColorName
